default_language_version:
  python: python3.12

default_stages: [pre-push]

repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.0
    hooks:
      - id: ruff
        args: [--fix, delphi/, tests/]
      - id: ruff-format
        args: [delphi/, tests/]

  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: pylint
        language: system
        types: [python]
        args: [delphi/, tests/]
