default_language_version:
  python: python3.12

default_stages: [pre-push]

repos:
  - repo: https://github.com/PyCQA/flake8
    rev: 7.1.1
    hooks:
      - id: flake8
        args: [delphi/, tests/]

  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: pylint
        language: system
        types: [python]
        args: [delphi/, tests/]
